[package]
name = "bitcoinleveldb-versioniterator"
version = "0.1.0"
authors = ["YourName <you@example.com>"]
license = "MIT"
edition = "2024"
description = "todo: write a description here"

# keywords = []
# categories = []

[build-dependencies.bitcoin-cfg]
path = "../bitcoin-cfg"
version = "0.1.19"

[dependencies]
bitcoinleveldb-slice = { path = "../bitcoinleveldb-slice" }
bitcoinleveldb-key = { path = "../bitcoinleveldb-key" }
bitcoinleveldb-iterator = { path = "../bitcoinleveldb-iterator" }
bitcoinleveldb-file = { path = "../bitcoinleveldb-file" }
bitcoinleveldb-status = { path = "../bitcoinleveldb-status" }
bitcoinleveldb-coding = { path = "../bitcoinleveldb-coding" }
bitcoinleveldb-meta = { path = "../bitcoinleveldb-meta" }

[dependencies.bitcoin-derive]
path = "../bitcoin-derive"
version = "0.1.19"

[dependencies.bitcoin-imports]
path = "../bitcoin-imports"
version = "0.1.19"


