[package]
name = "bitcoinleveldb-snapshot"
version = "0.1.0"
authors = ["YourName <you@example.com>"]
license = "MIT"
edition = "2024"
description = "todo: write a description here"

# keywords = []
# categories = []

[build-dependencies.bitcoin-cfg]
path = "../bitcoin-cfg"
version = "0.1.19"

[dependencies]
tracing.workspace = true
bitcoin-imports = { path = "../bitcoin-imports" }
bitcoinleveldb-key = { path = "../bitcoinleveldb-key" }
