[package]
name = "bitcoinleveldb-testenv"
version = "0.1.0"
authors = ["YourName <you@example.com>"]
license = "MIT"
edition = "2024"
description = "todo: write a description here"

# keywords = []
# categories = []

[dependencies]
traced-test.workspace = true
tracing.workspace = true
bitcoin-imports = { path = "../bitcoin-imports" }
bitcoinleveldb-env = { path = "../bitcoinleveldb-env" }
bitcoinleveldb-status = { path = "../bitcoinleveldb-status" }
bitcoinleveldb-slice = { path = "../bitcoinleveldb-slice" }
