[package]
name = "bitcoinsecp256k1-modinv"
version = "0.1.19"
authors = ["YourName <you@example.com>"]
license = "MIT"
edition = "2024"
description = "todo: write a description here"

# keywords = []
# categories = []

[dependencies]
bitcoinsecp256k1-modinv32 = { path = "../bitcoinsecp256k1-modinv32" }
bitcoinsecp256k1-modinv64 = { path = "../bitcoinsecp256k1-modinv64" }
bitcoin-imports = { path = "../bitcoin-imports" }
