[package]
name = "bitcoinleveldb-tablecache"
version = "0.1.0"
authors = ["YourName <you@example.com>"]
license = "MIT"
edition = "2024"
description = "todo: write a description here"

# keywords = []
# categories = []

[build-dependencies.bitcoin-cfg]
path = "../bitcoin-cfg"
version = "0.1.19"

[dependencies]
bitcoinleveldb-slice = { path = "../bitcoinleveldb-slice" }
bitcoinleveldb-options = { path = "../bitcoinleveldb-options" }
bitcoinleveldb-table = { path = "../bitcoinleveldb-table" }
bitcoinleveldb-file = { path = "../bitcoinleveldb-file" }
bitcoinleveldb-cache = { path = "../bitcoinleveldb-cache" }
bitcoinleveldb-status = { path = "../bitcoinleveldb-status" }
bitcoinleveldb-env = { path = "../bitcoinleveldb-env" }
bitcoinleveldb-iterator = { path = "../bitcoinleveldb-iterator" }
bitcoinleveldb-lru = { path = "../bitcoinleveldb-lru" }

[dependencies.bitcoin-derive]
path = "../bitcoin-derive"
version = "0.1.19"

[dependencies.bitcoin-imports]
path = "../bitcoin-imports"
version = "0.1.19"


