[package]
name = "bitcoinleveldb-tablerep"
version = "0.1.0"
authors = ["YourName <you@example.com>"]
license = "MIT"
edition = "2024"
description = "todo: write a description here"

# keywords = []
# categories = []

[build-dependencies.bitcoin-cfg]
path = "../bitcoin-cfg"
version = "0.1.19"

[dependencies]
bitcoinleveldb-options = { path = "../bitcoinleveldb-options" }
bitcoinleveldb-file = { path = "../bitcoinleveldb-file" }
bitcoinleveldb-status = { path = "../bitcoinleveldb-status" }
bitcoinleveldb-block = { path = "../bitcoinleveldb-block" }
bitcoinleveldb-blockhandle = { path = "../bitcoinleveldb-blockhandle" }
bitcoinleveldb-filter = { path = "../bitcoinleveldb-filter" }

[dependencies.bitcoin-derive]
path = "../bitcoin-derive"
version = "0.1.19"

[dependencies.bitcoin-imports]
path = "../bitcoin-imports"
version = "0.1.19"


