[package]
name = "bitcoinleveldb-versionsetutil"
version = "0.1.0"
authors = ["YourName <you@example.com>"]
license = "MIT"
edition = "2024"
description = "todo: write a description here"

# keywords = []
# categories = []

[dependencies]
tracing.workspace         = true
bitcoin-imports           = { path = "../bitcoin-imports" }
bitcoinleveldb-file       = { path = "../bitcoinleveldb-file" }
bitcoinleveldb-comparator = { path = "../bitcoinleveldb-comparator" }
bitcoinleveldb-slice      = { path = "../bitcoinleveldb-slice" }
bitcoinleveldb-options    = { path = "../bitcoinleveldb-options" }
bitcoinleveldb-iterator   = { path = "../bitcoinleveldb-iterator" }
bitcoinleveldb-key        = { path = "../bitcoinleveldb-key" }
bitcoinleveldb-tablecache = { path = "../bitcoinleveldb-tablecache" }
